- src/index.ts
Function `sha256base64` isn't exported.
> feat: expose `sha256base64` utility

- src/object-hash.ts
Instead of concatenating all the strings every time we call `toString`, just concatenate every time `write` is called:
```
hash({}) x 638,508 ops/sec ±1.21% (89 runs sampled)
hash(singleObject) x 94,972 ops/sec ±0.77% (93 runs sampled)
hash(tinyArray) x 10,008 ops/sec ±1.14% (90 runs sampled)
hash(mediumArray) x 961 ops/sec ±1.70% (89 runs sampled)
hash(largeArray) x 61.54 ops/sec ±1.55% (63 runs sampled)
hash(largeJson) x 1.90 ops/sec ±0.87% (9 runs sampled)
objectHash(largeJson, { unorderedObjects: true }) x 1.90 ops/sec ±0.76% (9 runs sampled)
```
To:
```
hash({}) x 789,862 ops/sec ±1.21% (88 runs sampled)
hash(singleObject) x 107,655 ops/sec ±1.33% (88 runs sampled)
hash(tinyArray) x 11,503 ops/sec ±0.84% (90 runs sampled)
hash(mediumArray) x 1,146 ops/sec ±1.08% (90 runs sampled) …
```
> perf(object-hash): avoid using array to just concatenate the string

- src/object-hash.ts
I did some tests and some values are fast by just leaving `'string' + value`, other values are slow, so I only change the values that shows a significant improvement.
```
'with toString x 243,790,997 ops/sec ±4.95% (88 runs sampled)',
'without toString x 1,138,995,770 ops/sec ±0.12% (94 runs sampled)',
'bool: with toString x 222,584,175 ops/sec ±0.11% (97 runs sampled)',
'bool: without toString x 1,142,979,415 ops/sec ±0.46% (94 runs sampled)',
'number: with toString x 110,618,185 ops/sec ±0.48% (94 runs sampled)',
'number: without toString x 1,148,295,991 ops/sec ±0.05% (99 runs sampled)',
'url: with toString x 11,248,050 ops/sec ±1.76% (84 runs sampled)',
'url: without toString x 4,678,286 ops/sec ±0.95% (94 runs sampled)', …
```
> perf(object-hash): avoid unnecessary `.toString()` on known values

- src/object-hash.ts
Use slice to check if the native function instead of using regex.
```
'oldRegex x 13,961,935 ops/sec ±2.56% (83 runs sampled)',
'endsWith x 43,583,325 ops/sec ±0.46% (94 runs sampled)',
'slice x 1,133,185,926 ops/sec ±0.59% (93 runs sampled)',
'for x 160,559,673 ops/sec ±0.15% (93 runs sampled)'
```
> Benchmark: [bench-is-native-function.js](https://gist.github.com/H4ad/0c8b3816ccf3de1506095f7257f62816#file-bench-is-native-function-js)
> perf(object-hash): faster isNativeFunction check

- src/object-hash.ts
Using slice again instead of Regex.
```
'oldRegex x 12,546,910 ops/sec ±2.65% (81 runs sampled)',
'slice x 1,135,283,250 ops/sec ±0.30% (97 runs sampled)'
```
> Benchmark: [bench-object-type.js](https://gist.github.com/H4ad/0c8b3816ccf3de1506095f7257f62816#file-bench-object-type-js)
> perf(object-hash): faster extract object type from toString

- src/object-hash.ts
V8 from what I could understand can predict when the same pattern is happening, but when we insert some randomness, the performance of string concatening is a little bit worse.
```
'oldObjectAccess x 1,141,640,736 ops/sec ±0.53% (97 runs sampled)',
'newObjectAccess x 1,146,221,890 ops/sec ±0.33% (97 runs sampled)',
'random: oldObjectAccess x 9,099,441 ops/sec ±1.14% (92 runs sampled)',
'random: newObjectAccess x 23,251,465 ops/sec ±1.63% (88 runs sampled)'
```
> Benchmark: [bench-object-access.js](https://gist.github.com/H4ad/0c8b3816ccf3de1506095f7257f62816#file-bench-object-access-js)
> perf(object-hash): faster object access by avoid string concat

- src/object-hash.ts
This one is good specially for big objects, using `Map` instead using `Array` this goes from:
```
hash({}) x 629,807 ops/sec ±1.22% (88 runs sampled)
hash(singleObject) x 93,377 ops/sec ±2.32% (90 runs sampled)
hash(tinyArray) x 10,114 ops/sec ±1.23% (88 runs sampled)
hash(mediumArray) x 981 ops/sec ±1.32% (87 runs sampled)
hash(largeArray) x 61.76 ops/sec ±1.70% (63 runs sampled)
hash(largeJson) x 1.90 ops/sec ±0.93% (9 runs sampled)
objectHash(largeJson, { unorderedObjects: true }) x 1.89 ops/sec ±1.15% (9 runs sampled)
```
To:
```
hash({}) x 667,828 ops/sec ±6.24% (78 runs sampled)
hash(singleObject) x 89,026 ops/sec ±1.10% (89 runs sampled)
hash(tinyArray) x 9,742 ops/sec ±1.09% (90 runs sampled)
hash(mediumArray) x 969 …
```
> perf(object-hash): faster circular checking by using map

- src/object-hash.ts
Just a tiny performance improvement to avoid allocate more memory and doing some spreading that is not necessary.
> perf(object-hash): reuse default options when is not passed

- src/object-hash.ts
If possible, I prefer to avoid splice and any other method to modify the array is is possible.
```
'splice x 8,139,878 ops/sec ±1.25% (89 runs sampled)',
'unshift x 7,932,324 ops/sec ±0.97% (94 runs sampled)',
'Array.prototype.push.apply x 14,664,082 ops/sec ±1.09% (90 runs sampled)'
```
> Benchmark: [bench-splice-vs-push-js](https://gist.github.com/H4ad/0c8b3816ccf3de1506095f7257f62816#file-bench-splice-vs-push-js)
> perf(object-hash): avoid splice method to insert values

- src/object-hash.ts
An an indirect dependency, this is the documentation I see most often and it was a bit confusing.
> docs: improve jsdoc for `objectHash()`

- README.md
- src/crypto/murmur.ts
- test/index.test.ts
* Fixes the `murmurHash` implementation by falling through all remainders as intended, instead of breaking.
* Removes an outdated JSDoc comment stating ASCII only for the data parameter, while it does in fact encode JavaScript strings using UTF-8 through TextEncoder().encode(), which matches how most other implementations do it.
* Updates the hash value produced by `murmurHash` in the README example.
* To prevent regression bugs, some basic test cases are added, covering seeds, UTF-8, Uint8Arrays, different input lengths, and the maximum safe seed value.
* Ensures compatibility with other implementations through testing known inputs, seeds, and outputs.
About 50% of the hashes produced by `murmurHash` prior to this fix are incorrect, so handle with care.
Resolves #82 and #11
> fix(murmurHash): fix murmurHash3 implementation, add tests

- README.md
- package.json
This PR makes the package size 1/2 by dropping legacy CommonJS support.
With Node.js and modern runtimes allowing mixed CommonJS + ESM usage, it should be less concern.
> build!: esm only

- README.md
- src/crypto/js/index.ts
- src/crypto/js/sha256.ts
- src/crypto/node/index.ts
- src/hash/hash.ts
- src/index.ts
- test/crypto.test.ts
Rename `sha256`/`sha256base64` into `stringDigest` with better description about algorithm.
Previous naming was confusing as digest is not exactly sha256+base64 (we trim `+/=` chars)
closes #85
> refactor!: rename `sha256*` to `stringDigest`

- README.md
- src/hash.ts
- src/index.ts
- src/serialize.ts
- src/utils/diff.ts
- src/utils/is-equal.ts
- test/ohash.test.ts
This PR renames `objectHash` to `serialize` which is closer to what it does (although serialization is not two way fully) -- also reduces confusion between `hash` <> [serialize util]
> refactor!: rename `objectHash` to `serialize`

- src/hash.ts
- src/serialize.ts
- test/hash.test.ts
- test/serialize.test.ts
This PR updates `hash` to always use `serialize` even for `string` inputs + adds a fast path for string serialization.
This avoids possibly conflicting hashes with the object and their serialized string as input. (to be backported for v1)
> fix(hash, serialize): always serialize string inputs 

- README.md
- src/hash.ts
- src/serialize.ts
- test/bundle.test.ts
- test/hash.test.ts
- test/serialize.test.ts
(rework #108)
before this PR `hash(input)` does serialize objects into a string before applying digest. If the same serialized string is passed to hash, the result will be the same, leading to potential unwanted collisions. 
This PR makes sure we always use the same serialization algorithm to avoid this. Performance overhead will be minimal with added fast-path for string inputs to `serialize`
BREAKING CHANGE: `hash(string)` will be different than before. As a replacement for backward compatible behavior, `digest(string).slice(0, 100)` can be used.
> fix(hash, serialize)!: always serialize string inputs

- README.md
- package.json
- src/index.ts
- src/utils/index.ts
Having extra utils (diff, isEqual) from main subpath adds to runtime eval overhead (however small)
This PR moves them under `ohash/utils` subpath export
> build!: move utils to `ohash/utils`

- README.md
- build.config.ts
- package.json
- src/hash.ts
- src/index.ts
- src/serialize.ts
- src/utils/diff.ts
- src/utils/is-equal.ts
- test/benchmarks.bench.ts
- test/bundle.test.ts
- test/hash.test.ts
- test/serialize.test.ts
Fully rewrite serializer as a class
- New simplified serialization system (check tests) (BREAKING BEHAVIOR)
- Type handlers are shared with the class prototype instead of creating per hash
- Common type handlers are added on runtime to reduce bundle size
- added tests with full coverage
- fixed various issues that were not working properly nor tested before such as Date handling
- Removed Node internal handlers
- Buffer is serialized as Uint8Array
- Map and Set keys are order-less by dedault
- Removed serialize options in favor of stable handling (please report an issue if you need back any!)
> refactor!: rewrite serializer

- src/crypto/node/index.ts
regression from #116 in 2.0.3
in (ESM) environments that `hash` named export does not exist from `node:crypto`, Node.js fails.
Using default export is also not best option as in environments with hybrid polyfills (nitro and cloudflare workers), it means whole exports (both native and polyfills) are pulled in unnecessarily.
This PR uses new Node.js `process.getBuiltinModule` API to fix it.
Also big surprise there is huge bump in benchmarks! `1,158,352.39` => `2,074,725.02` not really sure what deoptimization before was kicking in.. (from ESM perhaps?)
> fix: use `process.getBuiltinModule` to import fast hash

- src/serialize.ts
- test/bundle.test.ts
- test/serialize.test.ts
Resolves #120
- Added serialization tests for all typed arrays (except for `Float16Array` which is not yet supported, should we add it?)
- Corrected typos in Serializer 
- Added support for BigInt64Array and BigUint64Array
> fix: serialization format of typed arrays

- src/serialize.ts
Serialize sorts keys in objects/maps and values in Arrays and Sets. 
Map keys and Array/Set values to compare can be any type.
When both values (to compare) are string, it uses the fast path to avoid full serialization.
This PR makes use of fast path for wider cases (number, boolean, bigint, null, undefined) to use same fast path (it is same behavior of Array.sort()).
(only symbol, function and objects will go to full serializer after this change)
> perf(serialize): fast path to compare primitive values

- test/benchmarks.bench.ts
This PR adds proper benchmark for `serialize()` with presets.
```scala
✓ test/benchmarks.bench.ts > benchmarks > serialize 7423ms
name                                                            hz     min     max    mean     p75     p99    p995    p999     rme  samples
· count:1, size:small                                     477,263.18  0.0019  0.2646  0.0021  0.0020  0.0037  0.0039  0.0123  ±0.45%   238632   fastest
· count:1, size:small, circular:true                      308,090.19  0.0029  0.2285  0.0032  0.0032  0.0044  0.0055  0.0169  ±0.24%   154046
· count:1, size:large                                      43,778.31  0.0197  0.7381  0.0228  0.0217  0.0443  0.0572  0.5127  ±1.28%    21890
· count:1, size:large, circular:true                       25,026.26  0.0350  3.1461  0.0400 …
```
> test(benchmarks): add `serialize` presets

- README.md
- src/index.ts
ohash v1 has `isEqual` util from main `ohash` subpath. `isEqual` (alongside with `diff`) moved to `ohash/utils` in v2 with goal of adding more (less common) util from subpath so main usage has minimum runtime eval time.
However `isEqual` is exceptionally small and all of it's logic is shared with main subpath which makes no difference if exported _also_ from main subpath.
With this change, if two versions of ohash v1/v2 conflict in dependency tree, it will work.
> build: export `isEqual` from main subpath for backward compat

- src/serialize.ts
By removing the additional handlers added to `Serializer`  and handling them directly in `serialize()` we can further improve performance and reduce bundle size. I understand that this breaks the concept of this class but the performance gains worth it in my opinion.
`toComparableString()` can also be removed because `serialize()` will be much faster for simple types. (for comparing strings an additional flag is required to further improve performance)
```scala
✓ test/benchmarks.bench.ts > benchmarks > all presets 1260ms
name                  hz     min     max    mean     p75     p99    p995    p999     rme  samples
· serialize @ main  135.40  6.7750  9.9638  7.3853  7.5288  9.9638  9.9638  9.9638  ±2.03%       68
· serialize         171.57  5.3166  7.4802  5.8285  6.0204  7.4802  7.4802 …
```
> perf(serialize): faster serialization and less bundle size

- src/index.ts
ohash v2 renamed `sha256base64` to `digest` and `objectHash` to `serialize` however if ohash v1 is wrongly hoisted where ohash v2 is expected it can cause issues.
This PR adds alias subpath exports to ohash v1:
- `digest` => `sha256base64`
- `serialize` => `objectHash`
> build: add `digest` and `serialize` exports for forward compat (v1)

- src/serialize.ts
- test/serialize.test.ts
`Date.toISOString()` is much faster than `toJSON()` and returns the same format.
I benchmarked `serialize()` with additional 1000 date objects.
```scala
✓ test/benchmarks.bench.ts > benchmarks > Date 1785ms
name                          hz     min     max    mean     p75     p99    p995    p999     rme  samples
· Date.toISOString()  2,256,969.39  0.0004  0.2888  0.0004  0.0004  0.0008  0.0008  0.0015  ±0.40%  1128485   fastest
· Date.toJSON()       1,444,250.83  0.0006  0.1528  0.0007  0.0007  0.0011  0.0011  0.0015  ±0.14%   722126
BENCH  Summary
Date.toISOString() - test/benchmarks.bench.ts > benchmarks > Date
1.56x faster than Date.toJSON()
✓ test/benchmarks.bench.ts > benchmarks > all presets 1333ms
name                   hz      min      max     mean      p75      p99     p995 …
```
> perf(serialize): faster `Date` serialization

- src/serialize.ts
- test/serialize.test.ts
Fixes the following problem:
```ts
serialize(Object.create(null)); //TypeError: Cannot read properties of undefined (reading 'name')
```
> fix(serialize): handling objects with null constructors

- src/serialize.ts
- test/serialize.test.ts
I optimized serialization of `TypedArray` types: the previous parameter in these functions was `ArrayBufferLike` which did not allow calling `join()` directly on them. I inlined the proper types and also made `BigInt64Array` and  `BigUint64Array`  serialization much faster by not calling `map()` on them.
I refactored `serializeObject()` to avoid allocating new variables and calling `String.slice()` as much as possible.
In `compare()` I added back the fastest path for comparing strings because it is noticable faster for `Record<string, any>` types than calling `serialize()` twice to get the same string back. 
The first benchmark is compared to `main`, all the others are compared to the previous commit in this PR.
```scala
✓ test/benchmarks.bench.ts > benchmarks > count:1, size:large 1234ms …
```
> perf(serialize): faster serialization of typed arrays and objects with string keys

- src/serialize.ts
- test/serialize.test.ts
Closes #137 
We can check if the provided objects constructor is the same that's in the `globalThis` instead of just the name.
> fix(serialize): serializing custom classes

- src/serialize.ts
- test/serialize.test.ts
Currently the serializer can only handle object returns from `input.toJSON()`:
```ts
class TestString {
toJSON() {
return "value";
}
}
serialize(new TestString()); // Error: Cannot serialize String
```
There is no rule that `toJSON()` must return an `object` type.
For example: 
```ts
typeof new Date().toJSON(); // string
```
I added a fix that keeps the current output format for objects, but uses `TestString('value')` format for others.
> fix(serialize): allow `input.toJSON()` to return any type

- src/serialize.ts
- test/serialize.test.ts
Maps with object keys are currently serialized to wrong format.
```ts
const map = new Map();
map.set({ a: "b" }, "c");
serialize(map);  // Map{[object Object]:'c'}
```
I enabled serialization for every key in `serializeObjectEntries()` and fixed the wrong type of the `entries` param.
It now outputs: `Map{{a:'b'}:'c'}`
Added test to cover this (and also added more numeric keys to properly test the comparison within entries).
Added test where the `Map` entry key is the `Map` itself (circular).
> fix(serialize): `Map` serialization with object keys

- src/serialize.ts
A refactored `serializeObjectEntries()` to only accept `Array` types. This way we can avoid calling `Array.from()` on `Object.entries(object)` which returns `Array<[string, any]>`.
```sc
✓ test/benchmarks.bench.ts > benchmarks > serialize > count:256, size:small 1208ms
name                 hz     min     max    mean     p75     p99    p995    p999     rme  samples
· ohash v2.0.11  6,625.07  0.1373  2.9910  0.1509  0.1449  0.3059  0.3372  0.4453  ±1.30%     3313
· ohash @ dev    7,061.59  0.1302  0.6451  0.1416  0.1359  0.3135  0.3418  0.3891  ±0.72%     3531   fastest
BENCH  Summary
ohash @ dev - test/benchmarks.bench.ts > benchmarks > serialize > count:256, size:small
1.07x faster than ohash v2.0.11
clk: ~5.33 GHz
cpu: AMD Ryzen 9 7950X 16-Core Processor
runtime: bun 1.2.4 (x64-linux) …
```
> perf(serialize): faster object entries serialization

- README.md
Fix rendering of "important" callout under `serialize` section on readme
> docs: Fixed `important` callout in README

- src/serialize.ts
- test/bundle.test.ts
We can use `quickSort` for sorting `Set` and other arrays too.
```sc
✓ test/benchmarks.bench.ts > benchmarks > serialize - presets > count:1, size:small 2259ms
name                       hz     min     max    mean     p75     p99    p995    p999     rme  samples
· ohash @ 8434bea  3,842,100.95  0.0002  3.0409  0.0003  0.0003  0.0005  0.0006  0.0007  ±1.21%  1921051
· ohash @ dev      3,878,229.53  0.0002  2.0584  0.0003  0.0003  0.0004  0.0005  0.0008  ±0.86%  1939115   fastest
✓ test/benchmarks.bench.ts > benchmarks > serialize - presets > count:1, size:large 1219ms
name                    hz     min     max    mean     p75     p99    p995    p999     rme  samples
· ohash @ 8434bea  13,574.99  0.0626  2.9758  0.0737  0.0736  0.1290  0.1816  0.2739  ±1.27%     6788
· ohash @ dev …
```
> perf(serialize): use quick sort for sorting everything

- test/serialize.test.ts
Added more tests mainly to check if there are any differences in `workerd`. (https://github.com/unjs/ohash/pull/132)
Turns out that `URLSearchParams` is also broken (but our fallback properly handles that).
> test(serialize): added tests for more built-in types

- src/serialize.ts
Since we know `Object.entries(object)` returns `Array<[string, any]>` we can use a faster path to:
- avoid calling `compare()` because we can call `String.localeCompare()` directly on keys
- avoid calling `serialize()` for keys because they can be only strings
~~I created a new function for handling the `Iterable` but we can also merge it to the existing `serializeObjectEntries()` with a flag like `onlyStringKeys` and add conditions to handle that.~~
~~The performance gains are not significant though.~~ - Used a faster path later.
```sc
✓ test/benchmarks.bench.ts > benchmarks > serialize > count:1, size:small 1446ms
name                      hz     min     max    mean     p75     p99    p995    p999     rme  samples
· serialize @ main  703,004.23  0.0012  0.4631  0.0014  0.0013  0.0024 …
```
> perf(serialize): faster serialization of objects and classes
